# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js base image
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . /app

# Expose the port the app runs on
EXPOSE 8080

# Define environment variable for base URL and token
ENV BASE_URL=http://your-paperless-instance:8000
ENV TOKEN=your-api-token

# Command to run the application
CMD ["node", "src/index.js", "$BASE_URL", "$TOKEN"]
